version: '3'

services:
  jupyter:
    image: python:3.12.2-slim
    ports:
      - "8889:8888"
      - "8000:8001"
    volumes: 
      - ./notebook:/home/notebook
      - ./model:/model
    working_dir: /home/notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      mynetwork:
        aliases:
          - sb-network
    entrypoint: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

networks:
  mynetwork:
    name: sb-network
    driver: bridge